# Generated by Django 5.0.4 on 2024-04-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountMgt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employers',
            new_name='Employer',
        ),
    ]
