# Generated by Django 5.0.4 on 2024-04-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountMgt', '0002_rename_employers_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=30)),
                ('profile', models.CharField(max_length=50)),
                ('resume', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=30)),
                ('employerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountMgt.employer')),
            ],
        ),
    ]
