# Generated by Django 5.0.4 on 2024-04-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountMgt', '0003_candidate_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=30)),
                ('profile', models.CharField(max_length=50)),
                ('resume', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='firstName',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
