# Generated by Django 5.0.3 on 2024-04-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountMgt', '0004_jobseeker_delete_candidate_remove_recruiter_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(default='M', max_length=50),
        ),
    ]
