# Generated by Django 5.0.3 on 2024-04-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountMgt', '0005_jobseeker_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='email',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
