# Generated by Django 5.0.3 on 2024-04-20 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountMgt', '0004_jobseeker_delete_candidate_remove_recruiter_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('employerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountMgt.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobadvert.job')),
                ('skillId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobadvert.skill')),
            ],
        ),
    ]
