# Generated by Django 5.0.3 on 2024-04-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobadvert', '0002_rename_skill_skill_skillname'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='advertDate',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='job',
            name='closingDate',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='skill',
            name='sector',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillName',
            field=models.CharField(max_length=25),
        ),
    ]
